[atn]
devices = [0]

[ffn]
devices = [1, 2]

[scheduler]
ffn_concurrency = 2

[scheduler.slo]
ttft_ms = 1000
tbt_ms = 50

[[models]]
id = "Qwen/Qwen3-30B-A3B"
atn_tp_size = 1
atn_dp_size = 1
ffn_tp_size = 2
