[atn]
devices = [0, 1, 2, 3]

[ffn]
devices = [4, 5]

[scheduler]
ffn_concurrency = 1

[scheduler.slo]
ttft_ms = 1000
tbt_ms = 50

[[models]]
id = "Qwen/Qwen3-0.6B"
atn_tp_size = 1
atn_dp_size = 4
ffn_tp_size = 2
