[atn]
devices = [0]

[ffn]
devices = [1]

[scheduler]
ffn_concurrency = 1

[scheduler.slo]
ttft_ms = 1000
tbt_ms = 50

[[models]]
id = "Qwen/Qwen2.5-0.5B"
atn_tp_size = 1
atn_dp_size = 1
ffn_tp_size = 1

[[models]]
id = "Qwen/Qwen3-0.6B"
atn_tp_size = 1
atn_dp_size = 1
ffn_tp_size = 1
