[atn]
devices = [0, 1]

[ffn]
devices = [2]

[scheduler]
ffn_concurrency = 2

[scheduler.slo]
ttft_ms = 1000
tbt_ms = 50

[[models]]
id = "Qwen/Qwen2.5-0.5B"
atn_tp_size = 2
atn_dp_size = 1
ffn_tp_size = 1

[[models]]
id = "Qwen/Qwen3-0.6B"
atn_tp_size = 2
atn_dp_size = 1
ffn_tp_size = 1
